### ISSUE TITLE
直接放到项目中，报错

### ISSUE THREAD

**Issue by crdVincent** [maniackk/TimeProfiler#1]
直接放到项目中，报错

**Comment by maniackk** [comment]
耐心等待一下，最晚明天（6月30日），我会更新解决这个问题。我今天在做一个大的更新，增加耗时排序和耗时函数调用次数排序~最晚明天一起提上来。    感谢关注！

**Comment by maniackk** [comment]
增加头文件
#include "TimeProfiler/TPCallTrace.h"

记得在开始监控地方（比如appdelegate的didFinishLaunchingWithOptions方法里）
调用startTrace();方法。

我刚新建了工程，从github上下载代码。是可以运行的。请问报错信息是什么，然后一定记得加头文件并且
   调用startTrace();方法。

是iPhone5s及更新真机调试哈，不支持模拟器。
