### ISSUE TITLE
1.目前发现无法检测viewDidLoad, viewWillAppear 等一些UIViewController的方法。 2.因为修改过寄存器的调用上下文，崩溃时候获取不到完整的调用栈

### ISSUE THREAD

**Issue by chipengliu** [maniackk/TimeProfiler#10]
问题2图片
hook前
![image](https://user-images.githubusercontent.com/16236724/63569661-e6e00a80-c5ac-11e9-9daf-4a8d4bcf502b.png)

hook后
![image](https://user-images.githubusercontent.com/16236724/63569700-0d05aa80-c5ad-11e9-8f85-8597a2251d4a.png)

**Comment by maniackk** [comment]
1. 是因为里面有过滤，默认小于1000ms的方法，直接过滤了。你可以调用setCostMinTime方法，修改默认值。

**Comment by maniackk** [comment]
2. 目前也没有好的解决方法，我当时想的是，TimeProfiler也是线下debug使用，不可能到线上去。所以调用栈就没有要求一定全。你解决了这个问题了吗？或者有什么好的想法

**Comment by chipengliu** [comment]
我理解debug阶段也应该要保证堆栈完整，特别多人开发或开发阶段出线崩溃的时候堆栈信息比较重要。
解决方法可以看下这文章：
https://blog.gocy.tech/2019/07/08/hook-msgSend-advance/

**Comment by chipengliu** [comment]
堆栈丢失和过滤没直接关系，是内联汇编没有完成调用栈的回溯

**Comment by maniackk** [comment]
多谢，我周末研究一下，要是可行，我加上后，通知你。再次感谢！





------------------ 原始邮件 ------------------
发件人: Chipeng Liu <notifications@github.com&gt;
发送时间: 2019年9月6日 13:27
收件人: maniackk/TimeProfiler <TimeProfiler@noreply.github.com&gt;
抄送: maniac <wu_k_k@foxmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[maniackk/TimeProfiler] 1.目前发现无法检测viewDidLoad, viewWillAppear 等一些UIViewController的方法。 2.因为修改过寄存器的调用上下文，崩溃时候获取不到完整的调用栈 (#10)




我理解debug阶段也应该要保证堆栈完整，特别多人开发或开发阶段出线崩溃的时候堆栈信息比较重要。
 解决方法可以看下这文章：
 https://blog.gocy.tech/2019/07/08/hook-msgSend-advance/

**Comment by maniackk** [comment]
参考你给的[方案](https://blog.gocy.tech/2019/07/08/hook-msgSend-advance/),提交了临时解决方案， 9a3a60013acdbecc4f32060887543a9ae2f6cfd9 我最近也在看call frame,看下能不能像objc_msgsend一样，堆栈忽略fake_objc_msgSend_safe方法

**Comment by chipengliu** [comment]
> 参考你给的[方案](https://blog.gocy.tech/2019/07/08/hook-msgSend-advance/),提交了临时解决方案， [9a3a600](https://github.com/maniackk/TimeProfiler/commit/9a3a60013acdbecc4f32060887543a9ae2f6cfd9) 我最近也在看call frame,看下能不能像objc_msgsend一样，堆栈忽略fake_objc_msgSend_safe方法

这里感觉还需要对objc_msgSendSuper进行hook，否则一些系统提供的框架（如UIKit）是无法hook的，类似于viewDidLoad这样的方法

**Comment by maniackk** [comment]
是的，这个也是一个需要做的。

**Comment by maniackk** [comment]
感谢提的意见，我这个周末把这个加上去，其实之前有过想做，懒癌犯了，又忽略这件事~

**Comment by maniackk** [comment]
你好，已经支持super的统计了





------------------ 原始邮件 ------------------
发件人: Chipeng Liu <notifications@github.com&gt;
发送时间: 2019年9月17日 16:57
收件人: maniackk/TimeProfiler <TimeProfiler@noreply.github.com&gt;
抄送: maniac <wu_k_k@foxmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[maniackk/TimeProfiler] 1.目前发现无法检测viewDidLoad, viewWillAppear 等一些UIViewController的方法。 2.因为修改过寄存器的调用上下文，崩溃时候获取不到完整的调用栈 (#10)



 
参考你给的方案,提交了临时解决方案， 9a3a600 我最近也在看call frame,看下能不能像objc_msgsend一样，堆栈忽略fake_objc_msgSend_safe方法
  
这里感觉还需要对objc_msgSendSuper进行hook，否则一些系统提供的框架（如UIKit）是无法hook的，类似于viewDidLoad这样的方法
