### ISSUE TITLE
应用启动就崩溃了，可能是和Bugly冲突了

### ISSUE THREAD

**Issue by JinghuangLiu** [maniackk/TimeProfiler#11]
<img width="1198" alt="屏幕快照 2019-10-14 上午11 08 46" src="https://user-images.githubusercontent.com/6930613/66727646-27545a00-ee73-11e9-9582-fd617cd4d61b.png">

**Comment by dwbbytedance** [comment]
我这边也是，是[NSString stringWithFormat:]触发crash，估计参数形式不太一样。

**Comment by maniackk** [comment]
之前提交了 9a3a60013acdbecc4f32060887543a9ae2f6cfd9 ，维护CFI，但是在Xcode11，会导致[NSString stringWithFormat:]crash。我先去掉维护的CFI，目前已经可以正常使用，我再寻找一下维护CFI的方法
