### ISSUE TITLE
你好,hook底层方法 保存方法 会引起内存暴涨,怎么解决呢?

### ISSUE THREAD

**Issue by MoShenGuo** [maniackk/TimeProfiler#12]
你好 写的不错,我之前也发现直接hook底层,代码实现跟你这差不多的,但是有个问题,hook底层是记录在内存中(结构体保存),但是随着方法执行越来越多,运行越久的话,保存数据就越大,内存就会暴涨,但是你对里面指针不能重置,因为线程不安全,重置也导致崩溃,那你怎么解决呢?谢谢

**Comment by MoShenGuo** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/21171688/69312985-5082ba00-0c6b-11ea-9bf7-3f32ccf85c50.png">
你好 这里方法都是记录存储在结构体中,但是你停止监控方法 并没有对它进行清空,应该会越到后面 内存越大,不知道你有没有遇到过这样问题?谢谢

**Comment by maniackk** [comment]
目前是通过
void setMaxDepth(int depth){};
void setCostMinTime(uint64_t time){};
这两个函数来控制记录量的，不要所有函数都记录，通过设置深度跟耗时阈值，可以筛选出性能有问题的函数。根据工程来设置这两个值，不会出现内存暴涨情况，而且内存暴涨了，说明记录量太大了，本身会影响到App的运行，导致检测不准确。

**Comment by MoShenGuo** [comment]
我明白的意思,但是并没有解决本质问题,但是一直运行请求,也会出现暴涨了,我的意思 我定时取数据,取完数据后 再清空结构体数据缓存,怎么去清空结构图缓存呢
