### ISSUE TITLE
TimeProfilerVC 关闭后，程序80%概率会崩溃

### ISSUE THREAD

**Issue by FSilver** [maniackk/TimeProfiler#16]
显示崩溃位置 Tread 1  hook_msgSend

**Comment by maniackk** [comment]
您好，提供更详细的crash信息我吧。最好有个能复现的demo我~   感谢

**Comment by maniackk** [comment]
更新代码了，如果还有crash，欢迎加我微信（W343881414）。把crash详细信息给我，不然我也没法查~
