### ISSUE TITLE
打印的堆栈信息只有 TimeProfilerVC 相关的，没有工程中方法耗时

### ISSUE THREAD

**Issue by wuhahaBJ** [maniackk/TimeProfiler#17]
作者您好：麻烦关注下，是不是我没有调用对？
2　|　48.92ms　|　　　-[TimeProfilerVC　　getTPBtnWithFrame:title:sel:]
　1　|　48.95ms　|　　-[TimeProfilerVC　　RecordBtn]
　2　|　1.49ms　|　　　-[TimeProfilerVC　　getTPBtnWithFrame:title:sel:]
　1　|　1.508ms　|　　-[TimeProfilerVC　　costTimeSortBtn]
　2　|　2.154ms　|　　　-[TimeProfilerVC　　getTPBtnWithFrame:title:sel:]
　1　|　2.163ms　|　　-[TimeProfilerVC　　callCountSortBtn]
　2　|　2.255ms　|　　　-[UITableView　　initWithFrame:style:]
　1　|　2.383ms　|　　-[TimeProfilerVC　　tpTableView]

**Comment by maniackk** [comment]
你这个是放在demo里，还是在真实工程里？

**Comment by maniackk** [comment]
已经更新了，可以过滤不统计的类。默认过滤不统计TimeProfiler自身的类。

**Comment by wuhahaBJ** [comment]
> 你这个是放在demo里，还是在真实工程里？

放 demo 里的测试的，想测下效果，我理解demo和真实工程一样吧？
