### ISSUE TITLE
调用栈里如果有异常时会crash

### ISSUE THREAD

**Issue by ceekay1991** [maniackk/TimeProfiler#31]
![image](https://user-images.githubusercontent.com/4811245/132615510-e65c985e-570c-4a33-b620-13954bece6ea.png)
测试demo:https://github.com/ceekay1991/TimeProfiler/blob/master/TestException/TestException/ViewController.m

**Comment by Songcaili** [comment]
https://juejin.cn/post/7031016646508544037
