### ISSUE TITLE
大家对TimeProfiler有什么建议，或者需求。欢迎提出来

### ISSUE THREAD

**Issue by maniackk** [maniackk/TimeProfiler#6]
第一次玩开源，而且这个工具才开始弄不久。都是自己一边用一边想，其他开发者会有什么需求，然后自己开发。希望用过这个工具的同学，可以提出你们自己的想法和建议。我会及时响应你们的想法，只要合理，我都会尽力去满足大家的。

**Comment by maniackk** [comment]
对TimeProfiler的任何想法，都欢迎提出来~   你认为它有什么需要改进的，缺少什么功能等等。留言给我哦

**Comment by chipengliu** [comment]
我是从戴铭文章评论过来的。
>我写了arm64和iOS ABI，对汇编不熟，可以看下https://wukaikai.tech/ 。看完就知道戴老师写的hook源码~ 
=================楼下同学的疑问============================
今天看到大佬的课程，发现说的hook objc_msgSend的汇编部分，但是发现在教程中的部分和之前大神17年博客部分是一样的，都是InspectiveC/InspectiveCarm64.mm的汇编代码。然后跑去大神的github找到开源项目已阅，拿出里边hook objc_msgSend的汇编实现，然后有些部分不太理解。希望大神可以解答一下（这些是已阅里边拿出来的汇编）
1.为什么这里要把lr移到x2，x4移到x3呢？
__asm volatile ("mov x2, lr\n");
__asm volatile ("mov x3, x4\n");
2.为什么要在调用before_objc_msgSend，orig_objc_msgSend，after_objc_msgSend方法前后把x8，x9的值存入栈中呢？
__asm volatile ("stp x8, x9, [sp, #-16]!\n");
__asm volatile ("mov x12, %0\n" :: "r"(&before_objc_msgSend));
__asm volatile ("ldp x8, x9, [sp], #16\n");
3.为什么在三个方法执行完之后呢，最后x0会存储最后的函数返回地址呢？我打断点看到每次都是这样的，不太理解，然后把x0，移到lr确实是为了执行之前objc_msgSend执行后下一条执行的代码段段地址。
__asm volatile ("mov lr, x0\n");
==================================
这些疑问，都是对arm64汇编不太熟悉。

发现你工程是将原文中SMCallTraceCore.c进行了改写，将其中一些嵌入式汇编改成hardcode，但是没有说明评论下问题的原因:
1. `__asm volatile ("mov x3, x4\n");` x4覆盖x3的作用是什么？
2. 第二个问题中保存x8、x9的作用是什么？

看完你博客的文章，本人还是对第一个问题没有看懂？所以想问一下这里覆盖x3寄存器的作用是什么呢？而你的工程代码刚好省略了这一行嵌入式汇编代码，这里不会影响整个监控逻辑吗？

**Comment by maniackk** [comment]
1. __asm volatile ("mov x3, x4\n"); 这个没有必要，是多余的，可删除。
2. 第二句在真机翻译如下图，你可以看到读函数地址，会用到x8寄存器，所以需要保存x8寄存器，然后还原。为什么要stp x8, x9。那是因为sp mod 16 需要等于0。原因可以看我的另一篇博客:https://juejin.im/post/5d14623ef265da1bb47d7635  (你这里stp x7, x8也是可以的)
![image](https://user-images.githubusercontent.com/10388039/61132777-a2ae1480-a4ee-11e9-982d-909b7ff3ee51.png)
 
如果能解惑你的疑问，给个star呀~  多谢多谢

**Comment by maniackk** [comment]
> 我是从戴铭文章评论过来的。
> 
> > 我写了arm64和iOS ABI，对汇编不熟，可以看下https://wukaikai.tech/ 。看完就知道戴老师写的hook源码~
> > =================楼下同学的疑问============================
> > 今天看到大佬的课程，发现说的hook objc_msgSend的汇编部分，但是发现在教程中的部分和之前大神17年博客部分是一样的，都是InspectiveC/InspectiveCarm64.mm的汇编代码。然后跑去大神的github找到开源项目已阅，拿出里边hook objc_msgSend的汇编实现，然后有些部分不太理解。希望大神可以解答一下（这些是已阅里边拿出来的汇编）
> > 1.为什么这里要把lr移到x2，x4移到x3呢？
> > __asm volatile ("mov x2, lr\n");
> > __asm volatile ("mov x3, x4\n");
> > 2.为什么要在调用before_objc_msgSend，orig_objc_msgSend，after_objc_msgSend方法前后把x8，x9的值存入栈中呢？
> > __asm volatile ("stp x8, x9, [sp, #-16]!\n");
> > __asm volatile ("mov x12, %0\n" :: "r"(&before_objc_msgSend));
> > __asm volatile ("ldp x8, x9, [sp], #16\n");
> > 3.为什么在三个方法执行完之后呢，最后x0会存储最后的函数返回地址呢？我打断点看到每次都是这样的，不太理解，然后把x0，移到lr确实是为了执行之前objc_msgSend执行后下一条执行的代码段段地址。
> > __asm volatile ("mov lr, x0\n");
> > ==================================
> > 这些疑问，都是对arm64汇编不太熟悉。
> 
> 发现你工程是将原文中SMCallTraceCore.c进行了改写，将其中一些嵌入式汇编改成hardcode，但是没有说明评论下问题的原因:
> 
> 1. `__asm volatile ("mov x3, x4\n");` x4覆盖x3的作用是什么？
> 2. 第二个问题中保存x8、x9的作用是什么？
> 
> 看完你博客的文章，本人还是对第一个问题没有看懂？所以想问一下这里覆盖x3寄存器的作用是什么呢？而你的工程代码刚好省略了这一行嵌入式汇编代码，这里不会影响整个监控逻辑吗？

1. __asm volatile ("mov x3, x4\n"); 这个没有必要，是多余的，可删除。
2. 第二句在真机翻译如下图，你可以看到读函数地址，会用到x8寄存器，所以需要保存x8寄存器，然后还原。为什么要stp x8, x9。那是因为sp mod 16 需要等于0。原因可以看我的另一篇博客:https://juejin.im/post/5d14623ef265da1bb47d7635  (你这里stp x7, x8也是可以的)
![image](https://user-images.githubusercontent.com/10388039/61132777-a2ae1480-a4ee-11e9-982d-909b7ff3ee51.png)
 
如果能解惑你的疑问，给个star呀~  多谢多谢

**Comment by chipengliu** [comment]
> 1. __asm volatile ("mov x3, x4\n"); 这个没有必要，是多余的，可删除。
> 2. 第二句在真机翻译如下图，你可以看到读函数地址，会用到x8寄存器，所以需要保存x8寄存器，然后还原。为什么要stp x8, x9。那是因为sp mod 16 需要等于0。原因可以看我的另一篇博客:https://juejin.im/post/5d14623ef265da1bb47d7635  (你这里stp x7, x8也是可以的)
>    ![image](https://user-images.githubusercontent.com/10388039/61132777-a2ae1480-a4ee-11e9-982d-909b7ff3ee51.png)
> 
> 如果能解惑你的疑问，给个star呀~ 多谢多谢

我这么理解你看看是否正确：
首先前提是64位机器上，sp必须是16字节倍数级别地在内存地址移动进行申请新的内存区间(`sp mod 16 = 0`)；而`__asm volatile ("mov x12, %0\n" :: "r"(&before_objc_msgSend));`这样的内嵌汇编语句读取函数地址需要用到x8寄存器，也就是可能会影响到原来hook前x8寄存器上的值，故需要先保存到栈内存上；又因为x8只有8字节，所以需要和加上x9，凑齐16字节。

这里引申另外一个问题，在你另外一篇博文[iOS API](https://wukaikai.tech/2019/06/19/iOS-ABI/)中提到**iOS与官方arm64不同点**:
> 1. `void two_stack_args(char w0, char w1, char w2, char w3, char w4, char w5, char w6, char w7, char s0, char s1) {}`
s0在sp处占用1个字节，s1在sp + 1处占用1个字节。然后填充满足内存对齐（sp必须是16的倍数）。

这里iOS函数入参每个参数可以在内存上连续的，不需要每个参数单独占用8字节；而arm64是每个入参都需要一整个8字节区间?
```
iOS:
<-     8 bytes    ->  
 ------------------
|s0 s1 0 0 0 0 0 0 |
 ------------------
```
```
ARM64:
<-     8 bytes    -> <-    8 bytes    ->
 ------------------ ------------------
| s0 0 0 0 0 0 0 0 | s1 0 0 0 0 0 0 0 |
 ------------------  ------------------
```

---
已 star

这里可以提一个建议，其实可以考虑将监控日志做成图像可视化，类似golang里面的go profile火焰图，这样观察起来可能会更直观

**Comment by maniackk** [comment]
你的理解是正确的。关于建议：我是这样想的，先把基本需求做好，再优化显示之类的。这个库还有几个痛点功能，一直都想。但是最近工作特别忙，就停下来了。争取尽快把规划了的需求做了。

感谢你的建议，我后期会考虑的。

**Comment by yangzhixin1** [comment]
#接入crash
void hook_objc_msgSend_before(id self, SEL sel, uintptr_t lr)
{
    if (CallRecordEnable && pthread_main_np()) {
        pushCallRecord(object_getClass(self), sel);
    }
    
    setLRRegisterValue(lr);
}

Thread 28: EXC_BREAKPOINT (code=1, subcode=0x107f8b73c)

**Comment by maniackk** [comment]
必现还是偶现？

**Comment by yangzhixin1** [comment]
我接入到项目是必现的,接入戴老师的那一套 也是,新建的项目,没有问题,

**Comment by maniackk** [comment]
方便加个微信么，方便沟通找到问题。微信号：W343881414

**Comment by YouZoudeFish** [comment]
你好，新工程接入之后，把您demo里的btn的hidden都设置为YES之后，摇一摇之后xcode报这个错误
<img width="906" alt="image" src="https://user-images.githubusercontent.com/13774334/71615346-d17a8d00-2beb-11ea-8d34-429094636c4f.png">
然后手机上也没有任何显示。。。。请问是什么原因额？菜鸟一枚我是

**Comment by maniackk** [comment]
> > 1. __asm volatile ("mov x3, x4\n"); 这个没有必要，是多余的，可删除。
> > 2. 第二句在真机翻译如下图，你可以看到读函数地址，会用到x8寄存器，所以需要保存x8寄存器，然后还原。为什么要stp x8, x9。那是因为sp mod 16 需要等于0。原因可以看我的另一篇博客:https://juejin.im/post/5d14623ef265da1bb47d7635  (你这里stp x7, x8也是可以的)
> >    ![image](https://user-images.githubusercontent.com/10388039/61132777-a2ae1480-a4ee-11e9-982d-909b7ff3ee51.png)
> > 
> > 如果能解惑你的疑问，给个star呀~ 多谢多谢
> 
> 我这么理解你看看是否正确：
> 首先前提是64位机器上，sp必须是16字节倍数级别地在内存地址移动进行申请新的内存区间(`sp mod 16 = 0`)；而`__asm volatile ("mov x12, %0\n" :: "r"(&before_objc_msgSend));`这样的内嵌汇编语句读取函数地址需要用到x8寄存器，也就是可能会影响到原来hook前x8寄存器上的值，故需要先保存到栈内存上；又因为x8只有8字节，所以需要和加上x9，凑齐16字节。
> 
> 这里引申另外一个问题，在你另外一篇博文[iOS API](https://wukaikai.tech/2019/06/19/iOS-ABI/)中提到**iOS与官方arm64不同点**:
> 
> > 1. `void two_stack_args(char w0, char w1, char w2, char w3, char w4, char w5, char w6, char w7, char s0, char s1) {}`
> >    s0在sp处占用1个字节，s1在sp + 1处占用1个字节。然后填充满足内存对齐（sp必须是16的倍数）。
> 
> 这里iOS函数入参每个参数可以在内存上连续的，不需要每个参数单独占用8字节；而arm64是每个入参都需要一整个8字节区间?
> 
> ```
> iOS:
> <-     8 bytes    ->  
>  ------------------
> |s0 s1 0 0 0 0 0 0 |
>  ------------------
> ```
> 
> ```
> ARM64:
> <-     8 bytes    -> <-    8 bytes    ->
>  ------------------ ------------------
> | s0 0 0 0 0 0 0 0 | s1 0 0 0 0 0 0 0 |
>  ------------------  ------------------
> ```
> 
> 已 star
> 
> 这里可以提一个建议，其实可以考虑将监控日志做成图像可视化，类似golang里面的go profile火焰图，这样观察起来可能会更直观

老哥，是不是你问过我，让支持objc_msgSendSuper的统计？ 我忘记是谁在微信问了，现在已经支持了。需要欢迎自取
