### ISSUE TITLE
无法编译老哥

### ISSUE THREAD

**Issue by jin1050260** [maniackk/TimeProfiler#7]
ld: warning: directory not found for option '-L/Users/xiute/Desktop/TimeProfileProject/pdd_ios/Pods/PDDMediaCore/Effect/glm'
Undefined symbols for architecture arm64:
  "startTrace()", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by maniackk** [comment]
这个错误是因为没有真正引入TimeProfiler 。
![image](https://user-images.githubusercontent.com/10388039/60490523-44f11f80-9cd9-11e9-827c-e0458b021609.png)
你项目中，右键TimeProfiler，show in finder，看下TimeProfiler这个文件夹里面有没有源码，有源码的话，看下TimeProfiler这个文件夹是不是真的在工程的文件夹里。

**Comment by maniackk** [comment]
我找到一篇文章，专门说这个的。
![image](https://user-images.githubusercontent.com/10388039/60490802-db254580-9cd9-11e9-9a9d-e67f689bf6f9.png)
https://www.jianshu.com/p/a243b62b2e72
你可以参考下。要是解决了这个问题，留言告诉我下，我close issue。要是依然有问题，我看下
