### ISSUE TITLE
hook_objc_msgSend_before  crash

### ISSUE THREAD

**Issue by bigluo** [maniackk/TimeProfiler#9]
新建了一个工程，在appdelegate里添加了startTrace()

void hook_objc_msgSend_before(id self, SEL sel, uintptr_t lr)
{
    if (CallRecordEnable && pthread_main_np()) {
        pushCallRecord(object_getClass(self), sel);
    }
    
    setLRRegisterValue(lr);
}

hook_objc_msgSend_before这个方法运行了两次后就报错误：Thread 2: EXC_BREAKPOINT (code=1, subcode=0x1049c7be8)

**Comment by maniackk** [comment]
你好，你TPCallTrace.c改成了TPCallTrace.m了吗？
